# Generated by Django 5.1.4 on 2025-01-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('caller_name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], max_length=50)),
                ('recording', models.FileField(blank=True, null=True, upload_to='recordings/')),
            ],
        ),
    ]
