# Generated by Django 5.1.4 on 2025-01-07 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
