# Generated by Django 5.1.4 on 2025-01-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrecord',
            name='recording',
        ),
    ]
