# Generated by Django 5.1.4 on 2025-01-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_remove_callrecord_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
